# Generated by Django 2.1.3 on 2018-12-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='FECHA',
            field=models.CharField(max_length=50),
        ),
    ]
