# Generated by Django 2.1.3 on 2018-12-24 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20181224_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='FECHA',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
