# Generated by Django 2.1.4 on 2018-12-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20181224_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TIPO_PAGO',
            new_name='TipoPago',
        ),
    ]
