# Generated by Django 2.1.4 on 2019-01-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_detalle_total_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='VENDEDOR',
            field=models.CharField(default='Juanito Pérez', max_length=50),
            preserve_default=False,
        ),
    ]
