# Generated by Django 2.1.4 on 2019-01-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20190106_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ESTADO',
            field=models.BooleanField(default=False),
        ),
    ]
