# Generated by Django 2.1.4 on 2019-01-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='ESTADO',
            field=models.BooleanField(default=False),
        ),
    ]
