# Generated by Django 2.1.4 on 2019-01-19 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_auto_20190119_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='HORA',
            field=models.TimeField(blank=True, default=datetime.time(22, 46, 3, 436811)),
        ),
    ]
