# Generated by Django 2.1.4 on 2019-01-20 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_auto_20190119_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='FECHA',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 20)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='HORA',
            field=models.TimeField(blank=True, default=datetime.time(23, 47, 39, 554168)),
        ),
    ]
