# Generated by Django 2.1.4 on 2019-01-26 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_auto_20190120_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='FECHA',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 26)),
        ),
        migrations.AlterField(
            model_name='venta',
            name='HORA',
            field=models.TimeField(blank=True, default=datetime.time(23, 10, 38, 265058)),
        ),
    ]
