# Generated by Django 2.1.4 on 2018-12-06 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CANTIDAD_VALOR',
            fields=[
                ('COD_CV', models.IntegerField(primary_key=True, serialize=False)),
                ('CANTIDAD', models.IntegerField()),
                ('VALOR_TOTAL', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FORMATO',
            fields=[
                ('COD_FORMATO', models.IntegerField(primary_key=True, serialize=False)),
                ('CANTIDAD', models.IntegerField()),
                ('LITROS', models.FloatField()),
                ('TIPO_FORMATO', models.CharField(max_length=50)),
                ('DESCRIPTCION_FOR', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('ID_PROD', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=50)),
                ('PRECIO', models.IntegerField()),
                ('DESCRIPCION_PROD', models.CharField(max_length=50)),
                ('FORM_PROD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.FORMATO')),
            ],
        ),
        migrations.CreateModel(
            name='PROVEEDOR',
            fields=[
                ('RUT_PROV', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE_PROV', models.CharField(max_length=50)),
                ('TELEFONO_PROV', models.IntegerField()),
                ('DESCRIPCION_PROV', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='REGISTRO_BOD',
            fields=[
                ('COD_REG_BOD', models.IntegerField(primary_key=True, serialize=False)),
                ('DESCRIPCION_REG', models.CharField(max_length=50)),
                ('COD_PROV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.PROVEEDOR')),
                ('ID_PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.PRODUCTO')),
            ],
        ),
        migrations.AddField(
            model_name='cantidad_valor',
            name='ID_PRODUCTO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.PRODUCTO'),
        ),
    ]
