# Generated by Django 2.1.3 on 2018-12-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='FORMATO_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ID_PROD',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
