# Generated by Django 2.1.4 on 2018-12-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formato',
            old_name='TIPO_FORMATO',
            new_name='UNIDADES',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='FORM_PROD',
            new_name='FORMAT_PROD',
        ),
        migrations.RemoveField(
            model_name='formato',
            name='CANTIDAD',
        ),
        migrations.RemoveField(
            model_name='formato',
            name='CANT_P',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='DESCRIPCION_PROD',
        ),
    ]
