# Generated by Django 2.1.4 on 2019-01-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_registrobodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrobodega',
            name='CANTIDAD',
            field=models.IntegerField(default=0),
        ),
    ]
