# Generated by Django 2.1.4 on 2019-01-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20190107_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresoproducto',
            old_name='PEDIDO',
            new_name='NUMPEDIDO',
        ),
    ]
