# Generated by Django 2.1.4 on 2019-01-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20190108_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresoproducto',
            name='DESCRIPCION',
        ),
        migrations.AddField(
            model_name='ingresoproducto',
            name='ESTADO',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ESTADO',
            field=models.BooleanField(default=False),
        ),
    ]
