# Generated by Django 2.1.4 on 2019-01-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20190111_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ESTADO',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingresoproducto',
            name='CANTIDAD',
            field=models.IntegerField(default=0),
        ),
    ]
