# Generated by Django 2.1.4 on 2019-01-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20190117_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ESTADO',
        ),
    ]
